export { default as LogoFull } from "./image 7.svg";
export { default as Logo } from "./image 7 (1).svg";
export { default as Bill } from "./Bill.svg";
export { default as Setting } from "./user setting.svg";
export { default as SimCard } from "./sim-card 1.svg";
export { default as SimCard2 } from "./sim-card 1 (1).svg";
export { default as Phone } from "./Group 165.svg";
export { default as LogOut } from "./logout.svg";
export { default as usa } from "./usa.svg";
export { default as russia } from "./russia.svg";
export { default as israil } from "./israil.svg";
export { default as lineRight } from "./Vector 1 (Stroke).svg";
export { default as Voice } from "./vois.svg";
export { default as SMS } from "./sms.svg";
export { default as wifi } from "./wifi.svg";
export { default as smartphone } from "./smartphone .svg";
export { default as banner1 } from "./banner.png";
export { default as cardpay } from "./cardpay.png";
